"""Generate gradeable evaluation tasks from a server's tools, using the LLM."""

from __future__ import annotations

import json
from typing import Any

from openai import AsyncOpenAI
from pydantic import BaseModel, Field, ValidationError

from mcp_gauntlet.llm import chat_completion
from mcp_gauntlet.models import ToolInfo

# Bump when the wording below changes in a way that would produce a different task set.
# The cache key includes it, so a prompt fix invalidates task sets generated by the old
# prompt instead of silently serving them forever. (`.gauntlet/tasks/` is keyed per server,
# and a stale entry would make a prompt fix look like it did nothing.)
PROMPT_VERSION = "2"

_PROMPT = """\
You are designing an evaluation for an MCP (Model Context Protocol) server. Below \
are the tools the server exposes. Produce exactly {n} realistic, self-contained \
tasks that a user might ask an agent to perform, each solvable using one or more of \
these tools.

Rules:
- Only reference tools from the list below.
- NEVER invent an environment-specific identifier: a filesystem path, directory, \
repository location, database or table name, URL, URI, record ID, or user name. You \
do not know what exists on this server, and a task naming something that does not \
exist tests nothing — every call fails and a working server looks broken.
- Use identifiers ONLY if they appear under "Known context" below.
- If a task needs an identifier that is not given there, make its FIRST step a \
discovery call and phrase the task that way — "Discover which directories the server \
allows, then list the files in one of them", not "List the files in /workspace/data".
- Values you may always invent freely are ones the agent supplies rather than looks \
up: numbers to add, text to echo or transform, a search string.
- Prefer read-only / non-destructive tasks.
- The rubric must be objective and check the *substantive outcome* — correct \
values/results and appropriate tool use — that a grader can verify from the \
transcript. Do not require an exact output string unless producing that exact \
string is the point of the task. When the task begins with a discovery step, the \
rubric must grade what the agent did with what it found, not a specific value.

Tools:
{tools}

Known context:
{context}

Respond with JSON only, in this exact shape:
{{"tasks": [{{"description": "...", "rubric": "...", "expected_tools": ["tool_name"]}}]}}
"""

_NO_CONTEXT = (
    "(nothing known about this server's environment — every task must discover what it "
    "needs before using it)"
)


class EvalTask(BaseModel):
    description: str
    rubric: str = ""
    expected_tools: list[str] = Field(default_factory=list)


def _tools_blurb(tools: list[ToolInfo]) -> str:
    lines: list[str] = []
    for tool in tools:
        props: dict[str, Any] = {}
        if isinstance(tool.input_schema, dict):
            raw_props = tool.input_schema.get("properties")
            if isinstance(raw_props, dict):  # `or {}` wouldn't catch a truthy non-dict (a list)
                props = raw_props
        params = ", ".join(props.keys())
        desc = (tool.description or "").strip().replace("\n", " ")[:200]
        lines.append(f"- {tool.name}({params}): {desc}")
    return "\n".join(lines)


async def generate_tasks(
    client: AsyncOpenAI,
    model: str,
    tools: list[ToolInfo],
    n_tasks: int,
    context: str = "",
) -> list[EvalTask]:
    """Generate a task set, grounded in ``context`` — facts about this server's environment.

    Without grounding the model can only guess at paths, repositories and table names, and
    it guesses plausibly and wrongly: every call then fails and the *server* is scored for
    it. Servers whose tools take environment-specific identifiers were being graded a full
    letter or two below self-contained ones for exactly this reason.
    """
    prompt = _PROMPT.format(
        n=n_tasks, tools=_tools_blurb(tools), context=context.strip() or _NO_CONTEXT
    )
    try:
        completion = await chat_completion(
            client,
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            response_format={"type": "json_object"},
        )
    except Exception:  # noqa: BLE001 - a task-gen rate-limit/transport failure degrades to
        return []  # no tasks (→ inconclusive agentic eval); it must not crash the whole run
    if not completion.choices:
        return []
    content = completion.choices[0].message.content or "{}"
    try:
        data = json.loads(content)
    except json.JSONDecodeError:
        return []
    if not isinstance(data, dict):  # model returned a top-level array/scalar, not an object
        return []

    valid_names = {tool.name for tool in tools}
    tasks: list[EvalTask] = []
    raw_tasks = data.get("tasks")  # the model may emit a dict/scalar here, not a list
    for raw in (raw_tasks if isinstance(raw_tasks, list) else [])[:n_tasks]:
        if not isinstance(raw, dict):
            continue
        raw_expected = raw.get("expected_tools")  # may be null/scalar, not a list
        expected = [
            n for n in (raw_expected if isinstance(raw_expected, list) else []) if n in valid_names
        ]
        try:
            tasks.append(
                EvalTask(
                    description=str(raw["description"]),
                    rubric=str(raw.get("rubric", "")),
                    expected_tools=expected,
                )
            )
        except (KeyError, ValidationError):
            continue
    return tasks
